# Configurações do Camel
camel.spring.application.name=calme-portal-vt/api
camel.server.port=3000

# URL da API Java
java.url-api=http://localhost:8080/java-portal-vt/api/user

# Configurações da API do Google Maps
google-api-directions.url=https://maps.googleapis.com/maps/api/directions/json
google-api.key-api=
google-api.region=BR
google-api.language=pt-BR
google-api.units=metric
google-api.mode=transit
